wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1699064123.076571
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
